first version
bvg33/epam-tasks pull request #1
Opened 2021-04-06 15:33 UTC by bvg33

2021-04-06 18:17 UTC, AndreiRohau requested changes
Well done, left some comments, start adding changes, and feel free to ask questions or express concerns to me.

2021-04-06 18:17 UTC, AndreiRohau commented on Dao/src/main/java/com/epam/ems/config/MySqlDataBaseConfig.java
> +    private static final int MAX_OPEN_PREPARE_STATEMENTS = 100;
Вынести все в проперти файл

2021-04-06 18:17 UTC, AndreiRohau commented on Dao/src/main/java/com/epam/ems/config/HSQLDBConfig.java
> +public class HSQLDBConfig {
Напиши, зачем тебе этот конфиг?

2021-04-06 18:17 UTC, AndreiRohau commented on Dao/src/main/java/com/epam/ems/connection/ConnectionPool.java
> +//NO NEED
Зачем тут такой "класс"?

2021-04-06 18:17 UTC, AndreiRohau commented on Dao/src/main/java/com/epam/ems/dao/certificatedao/CertificateDaoImpl.java
> +    private static final String SORT_BY_DATE="sortByDate";
Это дупликация есть в других классах, создай отдельный класс с константами или ENUM с одним строковым полем.

2021-04-06 18:17 UTC, AndreiRohau commented on Dao/src/main/java/com/epam/ems/dao/certificatedao/CertificateDaoImpl.java
> +    private static JdbcTemplate TEMPLATE;
Why "static"?

2021-04-06 18:17 UTC, AndreiRohau commented on Dao/src/main/java/com/epam/ems/dao/certificatedao/CertificateDaoImpl.java
> +            throw new DaoException("there is no certificate with id="+id);
Add whitespaces 
[
id=" + id
]

2021-04-06 18:17 UTC, AndreiRohau commented on Dao/src/main/java/com/epam/ems/dao/certificatedao/CertificateDaoImpl.java
> +        if (tagIds != null) {
Change the following code with java internal functions: tagIds != null
[
nonNull(tagIds)
]
Check this everywhere in the code

2021-04-06 18:17 UTC, AndreiRohau commented on Web/src/main/java/com/epam/ems/controllers/TagsController.java
> +    public String createTag(@RequestParam MultiValueMap<String, String> allRequestParams) {
Create PUT|PATCH endpoint for "update" entity process

2021-04-06 18:17 UTC, AndreiRohau commented on Web/src/main/java/com/epam/ems/controllers/ExceptionsHandler.java
> +        return new ResponseEntity<>(errorResponse, HttpStatus.INTERNAL_SERVER_ERROR);
Where possible try not to use HttpStatus.INTERNAL_SERVER_ERROR just INTERNAL_SERVER_ERROR as static import.
Less code you write, easier for others to "read" and understand it.

2021-04-06 18:17 UTC, AndreiRohau commented on Web/src/main/java/com/epam/ems/controllers/CertificateController.java
> +        return "Certificate was successfully deleted";
Do not return simple String message as a result (use ResponseEntity<String>).
Look at the snippet below:

@GetMapping("/status")
ResponseEntity<String> statusCheck() {
    return new ResponseEntity<>(
      "Success", 
      HttpStatus.OK);
}

2021-04-06 18:17 UTC, AndreiRohau commented on Web/src/main/java/com/epam/ems/controllers/CertificateController.java
> +    public String updateCertificate(@PathVariable int id, @RequestParam MultiValueMap<String, String> allRequestParams) {
why do you need POST for create\update and PATCH?

2021-04-06 18:17 UTC, AndreiRohau commented on Dao/src/main/java/com/epam/ems/dao/tagdao/TagDaoImpl.java
> +    private static JdbcTemplate TEMPLATE;
Why static?

2021-04-06 18:17 UTC, AndreiRohau commented on Dao/src/main/java/com/epam/ems/dao/mapper/CertificateRowMapper.java
> +    private static final String TAG_NAME = "TAG_NAME";
Duplication

2021-04-06 18:17 UTC, AndreiRohau commented on Dao/src/main/java/com/epam/ems/dao/mapper/TagRowMapper.java
> +    private static final String ID = "id";
Duplication

2021-04-06 18:17 UTC, AndreiRohau commented on Dao/src/main/java/com/epam/ems/dao/tagdao/TagDaoImpl.java
> +        return new ArrayList<>();
Refactor method to "return" only once (to have only one exit point in method).

2021-04-06 18:17 UTC, AndreiRohau commented on Dao/src/main/java/com/epam/ems/dto/Certificate.java
> +    }
These are almost similar constructors. Use this() conctructor to remove duplications.

2021-04-06 18:17 UTC, AndreiRohau commented on Service/src/main/java/com/epam/ems/logic/creator/CertificateCreator.java
> +    private static final String DURATION = "duration";
Duplication

2021-04-06 18:17 UTC, AndreiRohau commented on Service/src/main/java/com/epam/ems/logic/creator/CertificateCreator.java
> +        return new Certificate(name, description, price, duration, currentDate, currentDate, tags);
Leave only 1 return statement!

2021-04-06 18:17 UTC, AndreiRohau commented on Service/src/main/java/com/epam/ems/logic/creator/CertificateCreator.java
> +        return 0;
Leave only 1 return statement!

2021-04-06 18:17 UTC, AndreiRohau commented on Service/src/main/java/com/epam/ems/logic/creator/CertificateCreator.java
> +        return null;
Leave only 1 return statement!

2021-04-06 18:17 UTC, AndreiRohau commented on Service/src/main/java/com/epam/ems/logic/creator/CertificateCreator.java
> +        return new ArrayList<>();
Leave only 1 return statement!

2021-04-06 18:17 UTC, AndreiRohau commented on Service/src/main/java/com/epam/ems/logic/creator/TagCreator.java
> +    private static final String NAME = "name";
Duplication

2021-04-06 18:17 UTC, AndreiRohau commented on Service/src/main/java/com/epam/ems/service/AbstractService.java
> +        return new String();
Leave only 1 return statement!

2021-04-06 18:17 UTC, AndreiRohau commented on Service/src/main/java/com/epam/ems/service/AbstractService.java
> +            return new ArrayList<>();
Leave only 1 return statement!

2021-04-06 18:17 UTC, AndreiRohau commented on Service/src/main/java/com/epam/ems/service/AbstractService.java
> +            return new ArrayList<>();
Leave only 1 return statement!

2021-04-06 18:17 UTC, AndreiRohau commented on Service/src/main/java/com/epam/ems/service/certificate/CertificateService.java
> +    private static final String SORT_BY_DATE_PARAM = "sortByDate";
Check for duplication

2021-04-06 18:17 UTC, AndreiRohau commented on Service/src/main/java/com/epam/ems/service/certificate/CertificateService.java
> +        return sortedByParam;
Leave only 1 return statement!

2021-04-06 18:17 UTC, AndreiRohau commented on Service/src/main/java/com/epam/ems/service/certificate/CertificateService.java
> +        return new ArrayList<>();
Leave only 1 return statement!

2021-04-06 18:17 UTC, AndreiRohau commented on Service/src/main/java/com/epam/ems/service/tag/TagServiceImpl.java
> +        return sortedByParam;
Leave only 1 return statement!

2021-04-06 18:17 UTC, AndreiRohau commented on Service/src/main/java/com/epam/ems/service/tag/TagServiceImpl.java
> +            return new ArrayList<>();
Leave only 1 return statement!

2021-04-09 15:05 UTC, AliakseiYermachonak commented on Dao/src/main/java/com/epam/ems/dao/extractor/CertificateFieldExtractor.java
> +        return null;
don't return null without processing it on the higher level

2021-04-12 10:05 UTC, closed without merging