module 3 first version
bvg33/epam-tasks pull request #2
Opened 2021-04-22 18:51 UTC by bvg33

2021-04-30 23:44 UTC, AndreiRohau requested changes
Nice work, almost everything is fine.
Most comments are connected to code convention rules and clean code agreements.
Close all comments ASAP and start preparing to Demo.
Later on I will send this Pull request to Alexei to double check my review.

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/config/MySqlDataBaseConfig.java
> +    @Autowired
Why do we need this annotation here?

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/config/MySqlDataBaseConfig.java
> +    @Autowired
Why do we need this annotation here?

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/CRDDao.java
> +//import com.epam.ems.exceptions.DaoException;
Remove unused lines.

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/certificatedao/CertificateDaoImpl.java
> +        if (param == SORT_BY_NAME) {
Use .equals() method

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/certificatedao/CertificateDaoImpl.java
> +        if (param == SORT_BY_DATE) {
Use .equals() method

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/certificatedao/CertificateDaoImpl.java
> +        name = "%" + name + "%";
Bad practice to change parameters value. Create another variable and call it properly.

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/certificatedao/CertificateDaoImpl.java
> +    private CriteriaBuilder criteriaBuilder;
This is not thread-safe - your class is a singleton.
Think what happens when several requests would process class variable?

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/certificatedao/CertificateDaoImpl.java
> +        if (sortType.equals("desc")) {
Make strings like "desc" a class field

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/certificatedao/CertificateDaoImpl.java
> +        } else if (sortType.equals("asc")) {
Make strings like "asc" a class field

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/orderdao/OrderDaoImpl.java
> +    private CriteriaBuilder criteriaBuilder;
This is not thread-safe usage...

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/tagdao/TagDaoImpl.java
> +    private CriteriaBuilder criteriaBuilder;
This is not thread-safe usage...

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/tagdao/TagDaoImpl.java
> +        name="%"+name+"%";
Bad practice to change method parameters - keep them immutable=final.

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/tagdao/TagDaoImpl.java
> +        entityManager.getTransaction().begin();
Why you use transaction manually and in annotation together?

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/tagdao/TagDaoImpl.java
> +        entityManager.getTransaction().begin();
Why you use transaction manually and in annotation together?

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/orderdao/OrderDaoImpl.java
> +        entityManager.getTransaction().begin();
Why you use transaction manually and in annotation together?

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/certificatedao/CertificateDaoImpl.java
> +        entityManager.getTransaction().begin();
Why you use transaction manually and in annotation together?

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/certificatedao/CertificateDaoImpl.java
> +        entityManager.getTransaction().begin();
Why you use transaction manually and in annotation together?

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/certificatedao/CertificateDaoImpl.java
> +        entityManager.getTransaction().begin();
Why you use transaction manually and in annotation together?

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/tagdao/TagDaoImpl.java
> +        if(sortType.equals("desc")) {
Keep strings static final

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/tagdao/TagDaoImpl.java
> +        }else if(sortType.equals("asc")){
Keep such strings static final

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/userdao/UserDaoImpl.java
> +    private CriteriaBuilder criteriaBuilder;
Not thread-safe

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dao/userdao/UserDaoImpl.java
> +        entityManager.getTransaction().begin();
Why you use transaction manually and in annotation together?

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dto/Certificate.java
> +    public Certificate() {
Please use Lombok here
Annotate class with @Data and other annotation where needed to remove boilerplate code.

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dto/Tag.java
> +public class Tag extends RepresentationModel<Tag> {
Lombok annotations, please.

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dto/User.java
> +public class User extends RepresentationModel<User> {
Lombok annotations.

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dto/UserOrderInfo.java
> +public class UserOrderInfo extends RepresentationModel {
Lombok

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dto/fields/Constants.java
> +    public static String OVERAGE_ORDER_PRICE="overageOrderPrice";
Why aren't these finals?
+ snippet is not clean: equal sign should have whitespaces

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dto/fields/Constants.java
> +public class Constants {
Naming convention tells us NOT to create classes in plural form e.g. user instead of users. Constant instead of Constants

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dto/lists/CertificateList.java
> +public class CertificateList extends RepresentationModel<CertificateList> {
Try using Lombok

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dto/lists/TagList.java
> +public class TagList extends RepresentationModel<TagList> {
Try using Lombok

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dto/lists/UserList.java
> +public class UserList extends RepresentationModel<UserList> {
Try using Lombok

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Dao/src/main/java/com/epam/ems/dto/lists/UserOrderInfoList.java
> +public class UserOrderInfoList extends RepresentationModel {
Try using Lombok

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/exceptions/NotEnoughMoneyException.java
> +public class NotEnoughMoneyException extends Exception {
Try using Lombok

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/logic/creator/CertificateRenovator.java
> +        if(name==null){
Not cleaned. Use Objects.isNull()

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/logic/creator/CertificateRenovator.java
> +            name=oldEntity.getName();
Not clean

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/logic/creator/CertificateRenovator.java
> +        if(description==null){
Not cleaned. Use Objects.isNull()

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/logic/creator/CertificateRenovator.java
> +            description=oldEntity.getDescription();
Not clean

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/logic/creator/CertificateRenovator.java
> +        if(price==0){
Clean up code

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/logic/creator/CertificateRenovator.java
> +        if(duration==0){
Clean up code

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/logic/creator/CertificateRenovator.java
> +            duration=oldEntity.getDuration();
Clean up code

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/logic/creator/CertificateRenovator.java
> +        if(tags==null){
Use isNull()

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/logic/handler/DateHandler.java
> +    private static final String PATTERN="yyyy-MM-dd'T'HH:mm";
Clean up this

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/logic/handler/DateHandler.java
> +@Component
Why @Component if all methods are static?

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/service/certificate/CertificateService.java
> +    private List<Certificate> getListSortedByParameter(MultiValueMap<String, String> allRequestParams,int page,int elements) {
Clean up

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/service/certificate/CertificateService.java
> +    public List<Certificate> doFilter(MultiValueMap<String, String> allRequestParams,int page,int elements) {
Clean up

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/service/tag/TagServiceImpl.java
> +@org.springframework.stereotype.Service
Remove whole path

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/service/tag/TagServiceImpl.java
> +    public List<Tag> doFilter(MultiValueMap<String, String> allRequestParams,int page,int elements) {
Clean up

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/service/tag/TagServiceImpl.java
> +    private List<Tag> getTagsSortedByNames(MultiValueMap<String, String> allRequestParams,int page,int elements) {
Clean up

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/service/user/UserService.java
> +    private DateHandler dateHandler;
No need in this resource - the required method is static.
Code convention says if we have a static method we have to call it using class, e.g. DateHandler.staticMethod();

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/service/user/UserService.java
> +    public List<User> getAllUsers(int page,int elements) {
Clean up code

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/service/user/UserService.java
> +    public List<Certificate> getUserCertificates(int id,int page,int elements) {
Clean up code

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/service/user/UserService.java
> +    public List<UserOrderInfo> getUserOrdersInfo(int id,int page,int elements) {
Clean up code

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/test/java/com/epam/ems/logic/serviceconfig/HSQLDBConfig.java
> +        em.setPackagesToScan(new String[]{"com.epam.ems"});
Make string class constant

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Service/src/test/java/com/epam/ems/logic/serviceconfig/HSQLDBConfig.java
> +                .addScript("fillTables.sql")
Make strings class constant

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Web/src/main/java/com/epam/ems/controllers/CertificateController.java
> +
Empty line

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Web/src/main/java/com/epam/ems/controllers/CertificateController.java
> +    public ResponseEntity updateCertificate(@Min(1) @PathVariable int id,@RequestBody Certificate certificate) {
Clean up code

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Web/src/main/java/com/epam/ems/controllers/CertificateController.java
> +    public ResponseEntity filter(@Min(1) @RequestParam int page,@Min(1) @RequestParam int elements,
Clean up code

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Web/src/main/java/com/epam/ems/controllers/TagsController.java
> +    public ResponseEntity AllTags(@Min(1) @RequestParam int page,@Min(1) @RequestParam int elements) {
Clean up code

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Web/src/main/java/com/epam/ems/controllers/TagsController.java
> +    public ResponseEntity<TagList> sortByParam(@Min(1) @RequestParam int page,@Min(1) @RequestParam int elements,
Clean up code

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Web/src/main/java/com/epam/ems/error/ErrorResponse.java
> +public class ErrorResponse {
Use Lombok

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Web/src/main/java/com/epam/ems/exceptions/MissingHeaderException.java
> +public class MissingHeaderException extends RuntimeException{
Use Lombok

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Web/src/main/java/com/epam/ems/hateoas/CertificatesControllerHateoas.java
> +        map.add("getByTagName", "tag");
Strings as a field

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Web/src/main/java/com/epam/ems/hateoas/CertificatesControllerHateoas.java
> +        entity.add(linkTo(CertificateController.class).slash("update").slash("id").withSelfRel());
Strings as a field

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Web/src/main/java/com/epam/ems/hateoas/TagControllerHateoas.java
> +        map.add("getByTagName", "tag");
Strings as a field

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Web/src/main/java/com/epam/ems/hateoas/TagControllerHateoas.java
> +        entity.add(linkTo(TagsController.class).slash("new").withSelfRel());
String as a field

2021-04-30 23:44 UTC, AndreiRohau commented on module_3/Web/src/main/java/com/epam/ems/hateoas/UsersControllerHateoas.java
> +public class UsersControllerHateoas implements Hateoas{
add a whitespace

2021-05-04 09:40 UTC, AliakseiYermachonak commented on module_3/Dao/src/main/java/com/epam/ems/dao/CRDDao.java
> +public interface CRDDao<T> {
CRD? Credentials? Credits? Creative runtime development?

2021-05-04 09:44 UTC, AliakseiYermachonak commented on module_3/Dao/src/main/java/com/epam/ems/dao/certificatedao/CertificateDaoImpl.java
> +    public void removeById(int id) {
Is it OK, to have void deletion?

2021-05-04 09:45 UTC, AliakseiYermachonak commented on module_3/Dao/src/main/java/com/epam/ems/dao/certificatedao/CertificateDaoImpl.java
> +    public void update(Certificate item) {
same, why void?

2021-05-04 09:46 UTC, AliakseiYermachonak commented on module_3/Dao/src/main/java/com/epam/ems/dao/tagdao/TagDaoImpl.java
> +        }
... else {
    ...  ?
}

2021-05-06 15:07 UTC, AndreiRohau approved these changes

2021-05-06 15:07 UTC, AndreiRohau commented on module_3/Service/src/main/java/com/epam/ems/service/userdetail/SecurityUserDetailService.java
> +        if (user == null) {
use isNull(user) - forget using equals sign

2021-05-06 15:07 UTC, AndreiRohau commented on module_3/Web/src/main/java/com/epam/ems/controllers/AuthController.java
> +        if (!isNull(userDetails) && encoder.matches(credentials.getPassword(), userDetails.getPassword())) {
!isNull
nonNull()

2021-05-06 15:07 UTC, merged